services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379

  mongodb-server:
    image: mongo:latest
    container_name: mongodb-server
    ports:
        - 27017:27017
